package com.hnqj.model;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.account
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.passwd
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.userid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.state
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Short state;


    private Short usertype;

    public Short getUsertype() {
        return usertype;
    }

    public void setUsertype(Short usertype) {
        this.usertype = usertype;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.usemobile
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Short usemobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.uid
     *
     * @return the value of tb_account.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.uid
     *
     * @param uid the value for tb_account.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.account
     *
     * @return the value of tb_account.account
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.account
     *
     * @param account the value for tb_account.account
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.passwd
     *
     * @return the value of tb_account.passwd
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.passwd
     *
     * @param passwd the value for tb_account.passwd
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.userid
     *
     * @return the value of tb_account.userid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.userid
     *
     * @param userid the value for tb_account.userid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.state
     *
     * @return the value of tb_account.state
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.state
     *
     * @param state the value for tb_account.state
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.usemobile
     *
     * @return the value of tb_account.usemobile
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Short getUsemobile() {
        return usemobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.usemobile
     *
     * @param usemobile the value for tb_account.usemobile
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUsemobile(Short usemobile) {
        this.usemobile = usemobile;
    }
}