package com.hnqj.model;

import java.util.Date;

public class Changelog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_changelog.loguid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String loguid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_changelog.logtype
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String logtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_changelog.recordid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String recordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_changelog.recordname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String recordname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_changelog.changetime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Date changetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_changelog.changeinfo
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String changeinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_changelog.userid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_changelog.ipaddress
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String ipaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_changelog.loguid
     *
     * @return the value of tb_changelog.loguid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getLoguid() {
        return loguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_changelog.loguid
     *
     * @param loguid the value for tb_changelog.loguid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setLoguid(String loguid) {
        this.loguid = loguid == null ? null : loguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_changelog.logtype
     *
     * @return the value of tb_changelog.logtype
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getLogtype() {
        return logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_changelog.logtype
     *
     * @param logtype the value for tb_changelog.logtype
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setLogtype(String logtype) {
        this.logtype = logtype == null ? null : logtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_changelog.recordid
     *
     * @return the value of tb_changelog.recordid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_changelog.recordid
     *
     * @param recordid the value for tb_changelog.recordid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid == null ? null : recordid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_changelog.recordname
     *
     * @return the value of tb_changelog.recordname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getRecordname() {
        return recordname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_changelog.recordname
     *
     * @param recordname the value for tb_changelog.recordname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setRecordname(String recordname) {
        this.recordname = recordname == null ? null : recordname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_changelog.changetime
     *
     * @return the value of tb_changelog.changetime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Date getChangetime() {
        return changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_changelog.changetime
     *
     * @param changetime the value for tb_changelog.changetime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setChangetime(Date changetime) {
        this.changetime = changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_changelog.changeinfo
     *
     * @return the value of tb_changelog.changeinfo
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getChangeinfo() {
        return changeinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_changelog.changeinfo
     *
     * @param changeinfo the value for tb_changelog.changeinfo
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setChangeinfo(String changeinfo) {
        this.changeinfo = changeinfo == null ? null : changeinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_changelog.userid
     *
     * @return the value of tb_changelog.userid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_changelog.userid
     *
     * @param userid the value for tb_changelog.userid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_changelog.ipaddress
     *
     * @return the value of tb_changelog.ipaddress
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_changelog.ipaddress
     *
     * @param ipaddress the value for tb_changelog.ipaddress
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress == null ? null : ipaddress.trim();
    }
}