package com.hnqj.model;

import java.util.Date;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_client.clintuid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String clintuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_client.clientname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String clientname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_client.phone
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_client.address
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String address;

    private String email;
    private String creator;
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_client.clintuid
     *
     * @return the value of tb_client.clintuid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getClintuid() {
        return clintuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_client.clintuid
     *
     * @param clintuid the value for tb_client.clintuid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setClintuid(String clintuid) {
        this.clintuid = clintuid == null ? null : clintuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_client.clientname
     *
     * @return the value of tb_client.clientname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getClientname() {
        return clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_client.clientname
     *
     * @param clientname the value for tb_client.clientname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setClientname(String clientname) {
        this.clientname = clientname == null ? null : clientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_client.phone
     *
     * @return the value of tb_client.phone
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_client.phone
     *
     * @param phone the value for tb_client.phone
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_client.address
     *
     * @return the value of tb_client.address
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_client.address
     *
     * @param address the value for tb_client.address
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public String getCreator() {
        return creator;
    }
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    public Date getCreatetime() {
        return createtime;
    }
    public void setCreatetime(Date createtime) {
        this.createtime = createtime ;
    }

}