package com.hnqj.model;

import java.math.BigDecimal;

public class Dealuidchild {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealuidchild.dealuid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String dealuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealuidchild.worksid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String worksid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealuidchild.worksprice
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private BigDecimal worksprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealuidchild.dealuid
     *
     * @return the value of tb_dealuidchild.dealuid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getDealuid() {
        return dealuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealuidchild.dealuid
     *
     * @param dealuid the value for tb_dealuidchild.dealuid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setDealuid(String dealuid) {
        this.dealuid = dealuid == null ? null : dealuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealuidchild.worksid
     *
     * @return the value of tb_dealuidchild.worksid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getWorksid() {
        return worksid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealuidchild.worksid
     *
     * @param worksid the value for tb_dealuidchild.worksid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setWorksid(String worksid) {
        this.worksid = worksid == null ? null : worksid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealuidchild.worksprice
     *
     * @return the value of tb_dealuidchild.worksprice
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public BigDecimal getWorksprice() {
        return worksprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealuidchild.worksprice
     *
     * @param worksprice the value for tb_dealuidchild.worksprice
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setWorksprice(BigDecimal worksprice) {
        this.worksprice = worksprice;
    }
}