package com.hnqj.model;

import java.util.Date;

public class Dealrecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealrecord.dealuid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String dealuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealrecord.dealtype
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String dealtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealrecord.businesstype
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String businesstype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealrecord.dealtime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Date dealtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealrecord.dealprice
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Long dealprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealrecord.dealstate
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String dealstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealrecord.businesid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String businesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealrecord.businesstbname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String businesstbname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealrecord.dealuid
     *
     * @return the value of tb_dealrecord.dealuid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getDealuid() {
        return dealuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealrecord.dealuid
     *
     * @param dealuid the value for tb_dealrecord.dealuid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setDealuid(String dealuid) {
        this.dealuid = dealuid == null ? null : dealuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealrecord.dealtype
     *
     * @return the value of tb_dealrecord.dealtype
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getDealtype() {
        return dealtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealrecord.dealtype
     *
     * @param dealtype the value for tb_dealrecord.dealtype
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setDealtype(String dealtype) {
        this.dealtype = dealtype == null ? null : dealtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealrecord.businesstype
     *
     * @return the value of tb_dealrecord.businesstype
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getBusinesstype() {
        return businesstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealrecord.businesstype
     *
     * @param businesstype the value for tb_dealrecord.businesstype
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setBusinesstype(String businesstype) {
        this.businesstype = businesstype == null ? null : businesstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealrecord.dealtime
     *
     * @return the value of tb_dealrecord.dealtime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Date getDealtime() {
        return dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealrecord.dealtime
     *
     * @param dealtime the value for tb_dealrecord.dealtime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setDealtime(Date dealtime) {
        this.dealtime = dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealrecord.dealprice
     *
     * @return the value of tb_dealrecord.dealprice
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Long getDealprice() {
        return dealprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealrecord.dealprice
     *
     * @param dealprice the value for tb_dealrecord.dealprice
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setDealprice(Long dealprice) {
        this.dealprice = dealprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealrecord.dealstate
     *
     * @return the value of tb_dealrecord.dealstate
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getDealstate() {
        return dealstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealrecord.dealstate
     *
     * @param dealstate the value for tb_dealrecord.dealstate
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setDealstate(String dealstate) {
        this.dealstate = dealstate == null ? null : dealstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealrecord.businesid
     *
     * @return the value of tb_dealrecord.businesid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getBusinesid() {
        return businesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealrecord.businesid
     *
     * @param businesid the value for tb_dealrecord.businesid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setBusinesid(String businesid) {
        this.businesid = businesid == null ? null : businesid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealrecord.businesstbname
     *
     * @return the value of tb_dealrecord.businesstbname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getBusinesstbname() {
        return businesstbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealrecord.businesstbname
     *
     * @param businesstbname the value for tb_dealrecord.businesstbname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setBusinesstbname(String businesstbname) {
        this.businesstbname = businesstbname == null ? null : businesstbname.trim();
    }
}