package com.hnqj.model;

public class Dict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.groupname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.keyname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String keyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.keyvalue
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String keyvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.parentid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.remarket
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String remarket;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.uid
     *
     * @return the value of tb_dict.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.uid
     *
     * @param uid the value for tb_dict.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.groupname
     *
     * @return the value of tb_dict.groupname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.groupname
     *
     * @param groupname the value for tb_dict.groupname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.keyname
     *
     * @return the value of tb_dict.keyname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getKeyname() {
        return keyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.keyname
     *
     * @param keyname the value for tb_dict.keyname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setKeyname(String keyname) {
        this.keyname = keyname == null ? null : keyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.keyvalue
     *
     * @return the value of tb_dict.keyvalue
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getKeyvalue() {
        return keyvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.keyvalue
     *
     * @param keyvalue the value for tb_dict.keyvalue
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setKeyvalue(String keyvalue) {
        this.keyvalue = keyvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.parentid
     *
     * @return the value of tb_dict.parentid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.parentid
     *
     * @param parentid the value for tb_dict.parentid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.remarket
     *
     * @return the value of tb_dict.remarket
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getRemarket() {
        return remarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.remarket
     *
     * @param remarket the value for tb_dict.remarket
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setRemarket(String remarket) {
        this.remarket = remarket == null ? null : remarket.trim();
    }
}