package com.hnqj.model;

import java.util.Date;

public class Findimg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_findimg.finduid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String finduid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_findimg.orderid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_findimg.describeinfo
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String describeinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_findimg.sendee
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String sendee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_findimg.checker
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String checker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_findimg.checktime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Date checktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_findimg.recivetime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Date recivetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_findimg.worksid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String worksid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_findimg.ordersstate
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String ordersstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_findimg.finishtime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Date finishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_findimg.price
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Long price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_findimg.finduid
     *
     * @return the value of tb_findimg.finduid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getFinduid() {
        return finduid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_findimg.finduid
     *
     * @param finduid the value for tb_findimg.finduid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setFinduid(String finduid) {
        this.finduid = finduid == null ? null : finduid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_findimg.orderid
     *
     * @return the value of tb_findimg.orderid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_findimg.orderid
     *
     * @param orderid the value for tb_findimg.orderid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_findimg.describeinfo
     *
     * @return the value of tb_findimg.describeinfo
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getDescribeinfo() {
        return describeinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_findimg.describeinfo
     *
     * @param describeinfo the value for tb_findimg.describeinfo
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setDescribeinfo(String describeinfo) {
        this.describeinfo = describeinfo == null ? null : describeinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_findimg.sendee
     *
     * @return the value of tb_findimg.sendee
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getSendee() {
        return sendee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_findimg.sendee
     *
     * @param sendee the value for tb_findimg.sendee
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setSendee(String sendee) {
        this.sendee = sendee == null ? null : sendee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_findimg.checker
     *
     * @return the value of tb_findimg.checker
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getChecker() {
        return checker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_findimg.checker
     *
     * @param checker the value for tb_findimg.checker
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setChecker(String checker) {
        this.checker = checker == null ? null : checker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_findimg.checktime
     *
     * @return the value of tb_findimg.checktime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_findimg.checktime
     *
     * @param checktime the value for tb_findimg.checktime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_findimg.recivetime
     *
     * @return the value of tb_findimg.recivetime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Date getRecivetime() {
        return recivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_findimg.recivetime
     *
     * @param recivetime the value for tb_findimg.recivetime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setRecivetime(Date recivetime) {
        this.recivetime = recivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_findimg.worksid
     *
     * @return the value of tb_findimg.worksid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getWorksid() {
        return worksid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_findimg.worksid
     *
     * @param worksid the value for tb_findimg.worksid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setWorksid(String worksid) {
        this.worksid = worksid == null ? null : worksid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_findimg.ordersstate
     *
     * @return the value of tb_findimg.ordersstate
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getOrdersstate() {
        return ordersstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_findimg.ordersstate
     *
     * @param ordersstate the value for tb_findimg.ordersstate
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setOrdersstate(String ordersstate) {
        this.ordersstate = ordersstate == null ? null : ordersstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_findimg.finishtime
     *
     * @return the value of tb_findimg.finishtime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Date getFinishtime() {
        return finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_findimg.finishtime
     *
     * @param finishtime the value for tb_findimg.finishtime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setFinishtime(Date finishtime) {
        this.finishtime = finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_findimg.price
     *
     * @return the value of tb_findimg.price
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_findimg.price
     *
     * @param price the value for tb_findimg.price
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setPrice(Long price) {
        this.price = price;
    }
}