package com.hnqj.model;

public class Integral {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade.uid
     *
     * @mbg.generated Thu Nov 23 13:50:05 CST 2017
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade.minimum
     *
     * @mbg.generated Thu Nov 23 13:50:05 CST 2017
     */
    private Integer mininum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade.maximum
     *
     * @mbg.generated Thu Nov 23 13:50:05 CST 2017
     */
    private Integer maxinum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade.grade
     *
     * @mbg.generated Thu Nov 23 13:50:05 CST 2017
     */
    private Integer grade;


    private Double divided;
    private Double basedeposit;

    public Double getDivided() {
        return divided;
    }

    public void setDivided(Double divided) {
        this.divided = divided;
    }

    public Double getBasedeposit() {
        return basedeposit;
    }

    public void setBasedeposit(Double basedeposit) {
        this.basedeposit = basedeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade.uid
     *
     * @return the value of tb_grade.uid
     *
     * @mbg.generated Thu Nov 23 13:50:05 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade.uid
     *
     * @param uid the value for tb_grade.uid
     *
     * @mbg.generated Thu Nov 23 13:50:05 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade.minimum
     *
     * @return the value of tb_grade.minimum
     *
     * @mbg.generated Thu Nov 23 13:50:05 CST 2017
     */
    public Integer getMininum() {
        return mininum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade.minimum
     *
     * @param mininum the value for tb_grade.minimum
     *
     * @mbg.generated Thu Nov 23 13:50:05 CST 2017
     */
    public void setMininum(Integer mininum) {
        this.mininum = mininum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade.maximum
     *
     * @return the value of tb_grade.maximum
     *
     * @mbg.generated Thu Nov 23 13:50:05 CST 2017
     */
    public Integer getMaxinum() {
        return maxinum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade.maximum
     *
     * @param maxinum the value for tb_grade.maximum
     *
     * @mbg.generated Thu Nov 23 13:50:05 CST 2017
     */
    public void setMaxinum(Integer maxinum) {
        this.maxinum = maxinum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade.grade
     *
     * @return the value of tb_grade.grade
     *
     * @mbg.generated Thu Nov 23 13:50:05 CST 2017
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade.grade
     *
     * @param grade the value for tb_grade.grade
     *
     * @mbg.generated Thu Nov 23 13:50:05 CST 2017
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }
}