package com.hnqj.model;

import java.util.Date;

public class Limit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_limit.uid
     *
     * @mbg.generated Thu Nov 23 15:03:29 CST 2017
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_limit.drawallimit
     *
     * @mbg.generated Thu Nov 23 15:03:29 CST 2017
     */
    private Integer drawallimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_limit.createtime
     *
     * @mbg.generated Thu Nov 23 15:03:29 CST 2017
     */
    private Date createtime;

    private Integer mininum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade.maximum
     *
     * @mbg.generated Thu Nov 23 13:50:05 CST 2017
     */
    private Integer maxinum;

    public Integer getMininum() {
        return mininum;
    }

    public void setMininum(Integer mininum) {
        this.mininum = mininum;
    }

    public Integer getMaxinum() {
        return maxinum;
    }

    public void setMaxinum(Integer maxinum) {
        this.maxinum = maxinum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_limit.uid
     *
     * @return the value of tb_limit.uid
     *
     * @mbg.generated Thu Nov 23 15:03:29 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_limit.uid
     *
     * @param uid the value for tb_limit.uid
     *
     * @mbg.generated Thu Nov 23 15:03:29 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_limit.drawallimit
     *
     * @return the value of tb_limit.drawallimit
     *
     * @mbg.generated Thu Nov 23 15:03:29 CST 2017
     */
    public Integer getDrawallimit() {
        return drawallimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_limit.drawallimit
     *
     * @param drawallimit the value for tb_limit.drawallimit
     *
     * @mbg.generated Thu Nov 23 15:03:29 CST 2017
     */
    public void setDrawallimit(Integer drawallimit) {
        this.drawallimit = drawallimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_limit.createtime
     *
     * @return the value of tb_limit.createtime
     *
     * @mbg.generated Thu Nov 23 15:03:29 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_limit.createtime
     *
     * @param createtime the value for tb_limit.createtime
     *
     * @mbg.generated Thu Nov 23 15:03:29 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}