package com.hnqj.model;

import java.util.Date;

public class Modules {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_modules.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_modules.pm_id
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String pmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_modules.md_name
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String mdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_modules.md_address
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String mdAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_modules.md_img
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String mdImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_modules.md_enabled
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Integer mdEnabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_modules.md_creator
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String mdCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_modules.md_ctime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Date mdCtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_modules.md_type
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Integer mdType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_modules.md_code
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String mdCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_modules.md_ordernum
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Short mdOrdernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_modules.md_method
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String mdMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_modules.md_ischild
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String mdIschild;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_modules.uid
     *
     * @return the value of tb_modules.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_modules.uid
     *
     * @param uid the value for tb_modules.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_modules.pm_id
     *
     * @return the value of tb_modules.pm_id
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getPmId() {
        return pmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_modules.pm_id
     *
     * @param pmId the value for tb_modules.pm_id
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setPmId(String pmId) {
        this.pmId = pmId == null ? null : pmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_modules.md_name
     *
     * @return the value of tb_modules.md_name
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getMdName() {
        return mdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_modules.md_name
     *
     * @param mdName the value for tb_modules.md_name
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setMdName(String mdName) {
        this.mdName = mdName == null ? null : mdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_modules.md_address
     *
     * @return the value of tb_modules.md_address
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getMdAddress() {
        return mdAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_modules.md_address
     *
     * @param mdAddress the value for tb_modules.md_address
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setMdAddress(String mdAddress) {
        this.mdAddress = mdAddress == null ? null : mdAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_modules.md_img
     *
     * @return the value of tb_modules.md_img
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getMdImg() {
        return mdImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_modules.md_img
     *
     * @param mdImg the value for tb_modules.md_img
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setMdImg(String mdImg) {
        this.mdImg = mdImg == null ? null : mdImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_modules.md_enabled
     *
     * @return the value of tb_modules.md_enabled
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Integer getMdEnabled() {
        return mdEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_modules.md_enabled
     *
     * @param mdEnabled the value for tb_modules.md_enabled
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setMdEnabled(Integer mdEnabled) {
        this.mdEnabled = mdEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_modules.md_creator
     *
     * @return the value of tb_modules.md_creator
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getMdCreator() {
        return mdCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_modules.md_creator
     *
     * @param mdCreator the value for tb_modules.md_creator
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setMdCreator(String mdCreator) {
        this.mdCreator = mdCreator == null ? null : mdCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_modules.md_ctime
     *
     * @return the value of tb_modules.md_ctime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Date getMdCtime() {
        return mdCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_modules.md_ctime
     *
     * @param mdCtime the value for tb_modules.md_ctime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setMdCtime(Date mdCtime) {
        this.mdCtime = mdCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_modules.md_type
     *
     * @return the value of tb_modules.md_type
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Integer getMdType() {
        return mdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_modules.md_type
     *
     * @param mdType the value for tb_modules.md_type
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setMdType(Integer mdType) {
        this.mdType = mdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_modules.md_code
     *
     * @return the value of tb_modules.md_code
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getMdCode() {
        return mdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_modules.md_code
     *
     * @param mdCode the value for tb_modules.md_code
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setMdCode(String mdCode) {
        this.mdCode = mdCode == null ? null : mdCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_modules.md_ordernum
     *
     * @return the value of tb_modules.md_ordernum
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Short getMdOrdernum() {
        return mdOrdernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_modules.md_ordernum
     *
     * @param mdOrdernum the value for tb_modules.md_ordernum
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setMdOrdernum(Short mdOrdernum) {
        this.mdOrdernum = mdOrdernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_modules.md_method
     *
     * @return the value of tb_modules.md_method
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getMdMethod() {
        return mdMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_modules.md_method
     *
     * @param mdMethod the value for tb_modules.md_method
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setMdMethod(String mdMethod) {
        this.mdMethod = mdMethod == null ? null : mdMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_modules.md_ischild
     *
     * @return the value of tb_modules.md_ischild
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getMdIschild() {
        return mdIschild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_modules.md_ischild
     *
     * @param mdIschild the value for tb_modules.md_ischild
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setMdIschild(String mdIschild) {
        this.mdIschild = mdIschild == null ? null : mdIschild.trim();
    }
}