package com.hnqj.model;

import java.util.Date;

public class Notify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notify.fid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notify.msg_type
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Short msgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notify.related_id
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String relatedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notify.msg_content
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String msgContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notify.msg_userid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String msgUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notify.msg_isread
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Short msgIsread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notify.msg_date
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Date msgDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notify.read_date
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Date readDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notify.fid
     *
     * @return the value of tb_notify.fid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notify.fid
     *
     * @param fid the value for tb_notify.fid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notify.msg_type
     *
     * @return the value of tb_notify.msg_type
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Short getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notify.msg_type
     *
     * @param msgType the value for tb_notify.msg_type
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setMsgType(Short msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notify.related_id
     *
     * @return the value of tb_notify.related_id
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getRelatedId() {
        return relatedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notify.related_id
     *
     * @param relatedId the value for tb_notify.related_id
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setRelatedId(String relatedId) {
        this.relatedId = relatedId == null ? null : relatedId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notify.msg_content
     *
     * @return the value of tb_notify.msg_content
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notify.msg_content
     *
     * @param msgContent the value for tb_notify.msg_content
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent == null ? null : msgContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notify.msg_userid
     *
     * @return the value of tb_notify.msg_userid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getMsgUserid() {
        return msgUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notify.msg_userid
     *
     * @param msgUserid the value for tb_notify.msg_userid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setMsgUserid(String msgUserid) {
        this.msgUserid = msgUserid == null ? null : msgUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notify.msg_isread
     *
     * @return the value of tb_notify.msg_isread
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Short getMsgIsread() {
        return msgIsread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notify.msg_isread
     *
     * @param msgIsread the value for tb_notify.msg_isread
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setMsgIsread(Short msgIsread) {
        this.msgIsread = msgIsread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notify.msg_date
     *
     * @return the value of tb_notify.msg_date
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Date getMsgDate() {
        return msgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notify.msg_date
     *
     * @param msgDate the value for tb_notify.msg_date
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setMsgDate(Date msgDate) {
        this.msgDate = msgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notify.read_date
     *
     * @return the value of tb_notify.read_date
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Date getReadDate() {
        return readDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notify.read_date
     *
     * @param readDate the value for tb_notify.read_date
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setReadDate(Date readDate) {
        this.readDate = readDate;
    }
}