package com.hnqj.model;

import java.util.Date;

public class Playimg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_playimg.playuid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String playuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_playimg.createtime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_playimg.imgurl
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_playimg.playsort
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Integer playsort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_playimg.navurl
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String navurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_playimg.playtype
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String playtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_playimg.typeremark
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String typeremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_playimg.creator
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_playimg.delflg
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String delflg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_playimg.playuid
     *
     * @return the value of tb_playimg.playuid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getPlayuid() {
        return playuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_playimg.playuid
     *
     * @param playuid the value for tb_playimg.playuid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setPlayuid(String playuid) {
        this.playuid = playuid == null ? null : playuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_playimg.createtime
     *
     * @return the value of tb_playimg.createtime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_playimg.createtime
     *
     * @param createtime the value for tb_playimg.createtime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_playimg.imgurl
     *
     * @return the value of tb_playimg.imgurl
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_playimg.imgurl
     *
     * @param imgurl the value for tb_playimg.imgurl
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_playimg.playsort
     *
     * @return the value of tb_playimg.playsort
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Integer getPlaysort() {
        return playsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_playimg.playsort
     *
     * @param playsort the value for tb_playimg.playsort
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setPlaysort(Integer playsort) {
        this.playsort = playsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_playimg.navurl
     *
     * @return the value of tb_playimg.navurl
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getNavurl() {
        return navurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_playimg.navurl
     *
     * @param navurl the value for tb_playimg.navurl
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setNavurl(String navurl) {
        this.navurl = navurl == null ? null : navurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_playimg.playtype
     *
     * @return the value of tb_playimg.playtype
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getPlaytype() {
        return playtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_playimg.playtype
     *
     * @param playtype the value for tb_playimg.playtype
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setPlaytype(String playtype) {
        this.playtype = playtype == null ? null : playtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_playimg.typeremark
     *
     * @return the value of tb_playimg.typeremark
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getTyperemark() {
        return typeremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_playimg.typeremark
     *
     * @param typeremark the value for tb_playimg.typeremark
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setTyperemark(String typeremark) {
        this.typeremark = typeremark == null ? null : typeremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_playimg.creator
     *
     * @return the value of tb_playimg.creator
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_playimg.creator
     *
     * @param creator the value for tb_playimg.creator
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_playimg.delflg
     *
     * @return the value of tb_playimg.delflg
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getDelflg() {
        return delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_playimg.delflg
     *
     * @param delflg the value for tb_playimg.delflg
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setDelflg(String delflg) {
        this.delflg = delflg == null ? null : delflg.trim();
    }
}