package com.hnqj.model;

import java.util.Date;

public class Rolesuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rolesuser.fid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rolesuser.role_id
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rolesuser.user_id
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rolesuser.role_creator
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String roleCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rolesuser.role_ctime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Date roleCtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rolesuser.fid
     *
     * @return the value of tb_rolesuser.fid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rolesuser.fid
     *
     * @param uid the value for tb_rolesuser.fid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rolesuser.role_id
     *
     * @return the value of tb_rolesuser.role_id
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rolesuser.role_id
     *
     * @param roleId the value for tb_rolesuser.role_id
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rolesuser.user_id
     *
     * @return the value of tb_rolesuser.user_id
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rolesuser.user_id
     *
     * @param userId the value for tb_rolesuser.user_id
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rolesuser.role_creator
     *
     * @return the value of tb_rolesuser.role_creator
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getRoleCreator() {
        return roleCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rolesuser.role_creator
     *
     * @param roleCreator the value for tb_rolesuser.role_creator
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setRoleCreator(String roleCreator) {
        this.roleCreator = roleCreator == null ? null : roleCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rolesuser.role_ctime
     *
     * @return the value of tb_rolesuser.role_ctime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Date getRoleCtime() {
        return roleCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rolesuser.role_ctime
     *
     * @param roleCtime the value for tb_rolesuser.role_ctime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setRoleCtime(Date roleCtime) {
        this.roleCtime = roleCtime;
    }
}