package com.hnqj.model;

import java.util.Date;

public class Shoppingcart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shoppingcart.uid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shoppingcart.userid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shoppingcart.workid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String workid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shoppingcart.workprice
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Float workprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shoppingcart.addtime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shoppingcart.uid
     *
     * @return the value of tb_shoppingcart.uid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shoppingcart.uid
     *
     * @param uid the value for tb_shoppingcart.uid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shoppingcart.userid
     *
     * @return the value of tb_shoppingcart.userid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shoppingcart.userid
     *
     * @param userid the value for tb_shoppingcart.userid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shoppingcart.workid
     *
     * @return the value of tb_shoppingcart.workid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getWorkid() {
        return workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shoppingcart.workid
     *
     * @param workid the value for tb_shoppingcart.workid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setWorkid(String workid) {
        this.workid = workid == null ? null : workid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shoppingcart.workprice
     *
     * @return the value of tb_shoppingcart.workprice
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Float getWorkprice() {
        return workprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shoppingcart.workprice
     *
     * @param workprice the value for tb_shoppingcart.workprice
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setWorkprice(Float workprice) {
        this.workprice = workprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shoppingcart.addtime
     *
     * @return the value of tb_shoppingcart.addtime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shoppingcart.addtime
     *
     * @param addtime the value for tb_shoppingcart.addtime
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}