package com.hnqj.model;

public class Sysconfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysconfig.cofiguid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String cofiguid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysconfig.groupname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysconfig.keyname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String keyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysconfig.keyvalue1
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String keyvalue1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysconfig.keyvalue2
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String keyvalue2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysconfig.keyvalue3
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String keyvalue3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysconfig.remarket
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String remarket;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysconfig.cofiguid
     *
     * @return the value of tb_sysconfig.cofiguid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getCofiguid() {
        return cofiguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysconfig.cofiguid
     *
     * @param cofiguid the value for tb_sysconfig.cofiguid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setCofiguid(String cofiguid) {
        this.cofiguid = cofiguid == null ? null : cofiguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysconfig.groupname
     *
     * @return the value of tb_sysconfig.groupname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysconfig.groupname
     *
     * @param groupname the value for tb_sysconfig.groupname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysconfig.keyname
     *
     * @return the value of tb_sysconfig.keyname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getKeyname() {
        return keyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysconfig.keyname
     *
     * @param keyname the value for tb_sysconfig.keyname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setKeyname(String keyname) {
        this.keyname = keyname == null ? null : keyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysconfig.keyvalue1
     *
     * @return the value of tb_sysconfig.keyvalue1
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getKeyvalue1() {
        return keyvalue1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysconfig.keyvalue1
     *
     * @param keyvalue1 the value for tb_sysconfig.keyvalue1
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setKeyvalue1(String keyvalue1) {
        this.keyvalue1 = keyvalue1 == null ? null : keyvalue1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysconfig.keyvalue2
     *
     * @return the value of tb_sysconfig.keyvalue2
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getKeyvalue2() {
        return keyvalue2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysconfig.keyvalue2
     *
     * @param keyvalue2 the value for tb_sysconfig.keyvalue2
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setKeyvalue2(String keyvalue2) {
        this.keyvalue2 = keyvalue2 == null ? null : keyvalue2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysconfig.keyvalue3
     *
     * @return the value of tb_sysconfig.keyvalue3
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getKeyvalue3() {
        return keyvalue3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysconfig.keyvalue3
     *
     * @param keyvalue3 the value for tb_sysconfig.keyvalue3
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setKeyvalue3(String keyvalue3) {
        this.keyvalue3 = keyvalue3 == null ? null : keyvalue3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysconfig.remarket
     *
     * @return the value of tb_sysconfig.remarket
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getRemarket() {
        return remarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysconfig.remarket
     *
     * @param remarket the value for tb_sysconfig.remarket
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setRemarket(String remarket) {
        this.remarket = remarket == null ? null : remarket.trim();
    }
}