package com.hnqj.model;

public class Userlevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userlevel.uid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userlevel.levelname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String levelname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userlevel.minintegral
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Integer minintegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userlevel.maxintergral
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private Integer maxintergral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userlevel.remark
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userlevel.uid
     *
     * @return the value of tb_userlevel.uid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userlevel.uid
     *
     * @param uid the value for tb_userlevel.uid
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userlevel.levelname
     *
     * @return the value of tb_userlevel.levelname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getLevelname() {
        return levelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userlevel.levelname
     *
     * @param levelname the value for tb_userlevel.levelname
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setLevelname(String levelname) {
        this.levelname = levelname == null ? null : levelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userlevel.minintegral
     *
     * @return the value of tb_userlevel.minintegral
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Integer getMinintegral() {
        return minintegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userlevel.minintegral
     *
     * @param minintegral the value for tb_userlevel.minintegral
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setMinintegral(Integer minintegral) {
        this.minintegral = minintegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userlevel.maxintergral
     *
     * @return the value of tb_userlevel.maxintergral
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public Integer getMaxintergral() {
        return maxintergral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userlevel.maxintergral
     *
     * @param maxintergral the value for tb_userlevel.maxintergral
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setMaxintergral(Integer maxintergral) {
        this.maxintergral = maxintergral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userlevel.remark
     *
     * @return the value of tb_userlevel.remark
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userlevel.remark
     *
     * @param remark the value for tb_userlevel.remark
     *
     * @mbg.generated Tue Dec 12 11:10:02 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}