package com.hnqj.model;

import java.io.Serializable;

public class Userinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.fristname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String fristname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.telephone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.iccode
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String iccode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.usrpicurl
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String usrpicurl;
/*
    private String idpic;

    private String idpicback;

    public String getIdpic() {
        return idpic;
    }

    public void setIdpic(String idpic) {
        this.idpic = idpic;
    }

    public String getIdpicback() {
        return idpicback;
    }

    public void setIdpicback(String idpicback) {
        this.idpicback = idpicback;
    }
*/
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.uid
     *
     * @return the value of tb_userinfo.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.uid
     *
     * @param uid the value for tb_userinfo.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.fristname
     *
     * @return the value of tb_userinfo.fristname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getFristname() {
        return fristname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.fristname
     *
     * @param fristname the value for tb_userinfo.fristname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setFristname(String fristname) {
        this.fristname = fristname == null ? null : fristname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.telephone
     *
     * @return the value of tb_userinfo.telephone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.telephone
     *
     * @param telephone the value for tb_userinfo.telephone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.iccode
     *
     * @return the value of tb_userinfo.iccode
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getIccode() {
        return iccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.iccode
     *
     * @param iccode the value for tb_userinfo.iccode
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setIccode(String iccode) {
        this.iccode = iccode == null ? null : iccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.usrpicurl
     *
     * @return the value of tb_userinfo.usrpicurl
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUsrpicurl() {
        return usrpicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.usrpicurl
     *
     * @param usrpicurl the value for tb_userinfo.usrpicurl
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUsrpicurl(String usrpicurl) {
        this.usrpicurl = usrpicurl == null ? null : usrpicurl.trim();
    }
}